export const IS_LOADING = 'IS_LOADING'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const SET_IS_DIAGNOSA = 'SET_IS_DIAGNOSA'
export const SET_FORM_REGISTER = 'SET_FORM_REGISTER'
export const CLEAR_FORM_REGISTER = 'CLEAR_FORM_REGISTER'

export const GET_DATA_METODE = 'GET_DATA_METODE'
export const SET_FUZZIFIKASI = 'SET_FUZZIFIKASI'